import { entries } from "@/lib/entries";
import { redirects } from "@/lib/redirects";
import { RESERVED_TOP } from "@/lib/reserved";
import type { Entry } from "@/lib/types";
import {
  entriesById,
  host,
  isRetired,
  primaryAddress,
  providerNav,
  resolveViewByPath,
} from "@/lib/views";

// The address shapes are derived from `Entry` rather than imported by name:
// src/lib/types.ts is generated by json2ts and gitignored, so `Entry` is the only
// name guaranteed to survive a schema edit or a generator upgrade.
type CurrentAddress = NonNullable<Entry["current"]>[number];
type PastAddress = NonNullable<Entry["history"]>[number];
type AkaMsPointer = NonNullable<Entry["aka_ms"]>[number];
type AlternateAddress = NonNullable<Entry["alternates"]>[number];

/** Which of an entry's four address arrays a link was found in. */
export type Where = "current" | "history" | "aka_ms" | "alternate";

const RANK: Record<Where, number> = {
  current: 0,
  history: 1,
  aka_ms: 2,
  alternate: 3,
};

/** Longest link we will look up. An unbounded path is echoed into the page. */
const MAX_LINK = 512;
/** Longest link we will render, so a pathological path can't wreck the layout. */
const DISPLAY_LIMIT = 200;

export interface AddressMatch {
  where: Where;
  /** Bare, exactly as stored in data/entries. */
  url: string;
  since?: string | undefined;
  note?: string | undefined;
  deprecated?: string | undefined;
  until?: string | undefined;
  became?: string | undefined;
  /** `became`, resolved back to whichever entry owns that URL today. */
  becameEntry?: EntryFacts | undefined;
  label?: string | undefined;
  verified?: string | undefined;
  environment?: string | undefined;
}

export interface EntryView {
  label: string;
  href: string;
}

export interface EntryFacts {
  /** Verbatim, so the JSON twin matches schemas/entry.json. */
  entry: Entry;
  retired: boolean;
  primary?: string | undefined;
  successor?: { entry: Entry; primary?: string | undefined } | undefined;
  views: EntryView[];
}

export interface AddressHit {
  match: AddressMatch;
  entry: EntryFacts;
}

interface Base {
  /** Exactly what was asked for. */
  input: string;
  /** The normalized form we actually looked up. */
  link: string;
  via?: "www-stripped" | undefined;
}

// Recursion is bounded by this shape, not by a depth counter: EntryFacts never
// embeds another EntryFacts (`successor` is a bare {entry, primary}), and
// `becameEntry` is the only nesting point — the EntryFacts it yields contains no
// AddressMatch. So the graph is Introspection -> AddressHit -> EntryFacts ->
// successor -> stop. A `became` cycle, or office.com's self-`became` back to the
// m365 entry that owns it, terminates by construction.
export type Introspection =
  | (Base & { kind: "empty" })
  | (Base & {
      kind: "redirect";
      namespace: string;
      slug: string;
      target: string;
      targetLink?: string | undefined;
      targetHit?: AddressHit | undefined;
      targetIsSelf: boolean;
      alsoIndexed?: AddressHit | undefined;
    })
  | (Base & { kind: "address"; hit: AddressHit; otherHits: AddressHit[] })
  | (Base & { kind: "host"; host: string; addresses: AddressHit[] })
  | (Base & { kind: "unknown"; host?: string | undefined });

/**
 * Bare, comparable form of whatever the reader pasted. Always surfaced back on the
 * page, which is what lets it normalize aggressively and stay honest.
 *
 * Case is preserved. src/fetch.ts looks up `redirects` without lowercasing, so the
 * redirect map really is case-sensitive; lowercasing here would make this page
 * promise a redirect that aka.dog/{Who}/{Slug} actually 404s. The index lookup
 * lowercases separately, at the point of comparison.
 */
export const normalizeLink = (raw: string): string =>
  raw
    .trim()
    // Query and fragment are never stored, so keeping them guarantees a miss.
    .replace(/[#?][\s\S]*$/, "")
    // http/https only. A generic scheme regex would silently swallow a mailto:
    // or ftp: input that deserves an honest "we don't know this".
    // One slash or two: a pasted "https://office.com" reaches us as
    // "https:/office.com", because the path layer collapses the double slash
    // before the route ever sees it.
    .replace(/^https?:\/\/?/i, "")
    .replace(/^\/+|\/+$/g, "");

/**
 * Decode once. A malformed sequence ("%E0%A4%A") throws URIError, and the honest
 * answer there is "nothing known about this link", not a 500.
 */
const safeDecode = (value: string): string => {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
};

/** Truncate for display only — never for lookup. */
export const forDisplay = (link: string): string =>
  link.length > DISPLAY_LIMIT ? `${link.slice(0, DISPLAY_LIMIT - 1)}…` : link;

interface AddressRef {
  where: Where;
  entry: Entry;
  address: CurrentAddress | PastAddress | AkaMsPointer | AlternateAddress;
}

// Two maps over ~130 addresses, built once per isolate. Linear in entry count and
// cheap enough to stay at module scope; don't move this into the request path.
const addressIndex = new Map<string, AddressRef[]>();
const hostIndex = new Map<string, AddressRef[]>();

const push = (
  index: Map<string, AddressRef[]>,
  key: string,
  ref: AddressRef,
) => {
  const bucket = index.get(key);
  if (bucket) bucket.push(ref);
  else index.set(key, [ref]);
};

for (const entry of entries) {
  const refs: AddressRef[] = [
    ...(entry.current ?? []).map(
      (address): AddressRef => ({ where: "current", entry, address }),
    ),
    ...(entry.history ?? []).map(
      (address): AddressRef => ({ where: "history", entry, address }),
    ),
    ...(entry.aka_ms ?? []).map(
      (address): AddressRef => ({ where: "aka_ms", entry, address }),
    ),
    ...(entry.alternates ?? []).map(
      (address): AddressRef => ({ where: "alternate", entry, address }),
    ),
  ];
  for (const ref of refs) {
    push(addressIndex, ref.address.url.toLowerCase(), ref);
    push(hostIndex, host(ref.address.url).toLowerCase(), ref);
  }
}

// providerNav() is called once, not per hit.
const NAV = providerNav();

/**
 * Every /index/* page this entry actually appears on. The membership question is
 * put to resolveViewByPath itself rather than re-derived, so the
 * curated-page-shadows-a-collection rule can never drift out of sync. The slugs
 * come from providerNav(), so the resolver cannot throw here.
 */
const viewsFor = (entry: Entry): EntryView[] => {
  const views: EntryView[] = [
    { label: entry.provider, href: `/index/${entry.provider}` },
  ];
  const nav = NAV.find((group) => group.provider === entry.provider);
  for (const collection of nav?.collections ?? [])
    if (
      resolveViewByPath([entry.provider, collection.slug]).entries.some(
        (candidate) => candidate.id === entry.id,
      )
    )
      views.push({
        label: collection.title,
        href: `/index/${entry.provider}/${collection.slug}`,
      });
  if (isRetired(entry) || (entry.history?.length ?? 0) > 0)
    views.push({
      label: "deprecated",
      href: `/index/${entry.provider}/deprecated`,
    });
  return views;
};

const factsFor = (entry: Entry): EntryFacts => {
  const successorEntry = entry.superseded_by
    ? entriesById.get(entry.superseded_by)
    : undefined;
  return {
    entry,
    retired: isRetired(entry),
    primary: primaryAddress(entry),
    successor: successorEntry
      ? { entry: successorEntry, primary: primaryAddress(successorEntry) }
      : undefined,
    views: viewsFor(entry),
  };
};

/** The first entry that lists `url` as a current address, else any that knows it. */
const ownerOf = (url: string): Entry | undefined => {
  const refs = addressIndex.get(normalizeLink(url).toLowerCase()) ?? [];
  const ranked = [...refs].sort((a, b) => RANK[a.where] - RANK[b.where]);
  return ranked[0]?.entry;
};

const toMatch = (ref: AddressRef): AddressMatch => {
  const address = ref.address;
  const past = ref.where === "history" ? (address as PastAddress) : undefined;
  const pointer =
    ref.where === "aka_ms" ? (address as AkaMsPointer) : undefined;
  const alternate =
    ref.where === "alternate" ? (address as AlternateAddress) : undefined;
  const becameOwner = past?.became ? ownerOf(past.became) : undefined;
  return {
    where: ref.where,
    url: address.url,
    since: "since" in address ? address.since : undefined,
    note: "note" in address ? address.note : undefined,
    deprecated: past?.deprecated,
    until: past?.until,
    became: past?.became,
    becameEntry: becameOwner ? factsFor(becameOwner) : undefined,
    label: pointer?.label,
    verified: pointer?.verified,
    environment: alternate?.environment,
  };
};

const toHit = (ref: AddressRef): AddressHit => ({
  match: toMatch(ref),
  entry: factsFor(ref.entry),
});

/** Exact-address hits for a normalized link, best bucket first. */
const lookupAddress = (link: string): AddressHit[] => {
  const refs = addressIndex.get(link.toLowerCase()) ?? [];
  return [...refs].sort((a, b) => RANK[a.where] - RANK[b.where]).map(toHit);
};

function lookup(input: string, link: string): Introspection {
  const base: Base = { input, link };

  // Mirrors the guard at src/fetch.ts, so introspection never claims a redirect
  // the Worker would refuse to serve. `who` is a filename and a slug may contain
  // slashes, so the whole remainder is the key — never assume two segments.
  if (!RESERVED_TOP.has(link.split("/")[0] ?? "")) {
    const target = redirects.get(link);
    if (target !== undefined) {
      const separator = link.indexOf("/");
      const targetLink = /^https?:\/\//i.test(target)
        ? normalizeLink(target)
        : undefined;
      const targetIsSelf = targetLink
        ? /^(www\.)?aka\.dog(\/|$)/i.test(targetLink)
        : false;
      // One level, and never back through the redirect map: a short link whose
      // target is another aka.dog URL must not recurse. The page offers the
      // reader a link to follow by hand instead.
      const targetHit =
        targetLink && !targetIsSelf ? lookupAddress(targetLink)[0] : undefined;
      return {
        ...base,
        kind: "redirect",
        namespace: separator === -1 ? link : link.slice(0, separator),
        slug: separator === -1 ? "" : link.slice(separator + 1),
        target,
        targetLink,
        targetHit,
        targetIsSelf,
        // The same string, asked of the other system: a link can be both a
        // valid who/slug and a tracked address, and hiding either would lie.
        alsoIndexed: lookupAddress(link)[0],
      };
    }
  }

  const addresses = lookupAddress(link);
  const [hit, ...otherHits] = addresses;
  if (hit) return { ...base, kind: "address", hit, otherHits };

  const linkHost = host(link);
  const sameHost = hostIndex.get(linkHost.toLowerCase()) ?? [];
  if (sameHost.length > 0)
    return {
      ...base,
      kind: "host",
      host: linkHost,
      addresses: [...sameHost]
        .sort((a, b) => RANK[a.where] - RANK[b.where])
        .map(toHit),
    };

  return { ...base, kind: "unknown", host: linkHost || undefined };
}

export function introspect(raw: string): Introspection {
  const link = normalizeLink(raw);
  if (!link) return { kind: "empty", input: raw, link };
  if (link.length > MAX_LINK)
    return { kind: "unknown", input: raw, link: link.slice(0, MAX_LINK) };

  const result = lookup(raw, link);
  // One retry, never two. `www.office.com` is a distinct host from `office.com`,
  // so stripping it unconditionally would make a www-hosted entry unreachable;
  // a second chance after a miss costs nothing and hides nothing.
  if (result.kind === "unknown" && /^www\./i.test(link)) {
    const retried = lookup(raw, link.slice(4));
    if (retried.kind !== "unknown") return { ...retried, via: "www-stripped" };
  }
  return result;
}

const PREFIX = /^\/?introspect(?=\/|$)/;

/**
 * The single entry point for all three callers, so the link is decoded exactly
 * once and every call site hands the resolver the same input shape.
 * `Astro.params.link` is deliberately unused: a second decode would corrupt a
 * link containing a literal %20.
 */
export function introspectPathname(pathname: string): Introspection {
  // `.json` comes off BEFORE the prefix: "/introspect.json" must reduce to "",
  // and PREFIX's lookahead won't match while the suffix is still attached.
  // It also means that if Astro ever hands the HTML route a `.json` URL, the
  // reader gets the right answer in the wrong content type rather than a
  // bogus "nothing known about office.com.json".
  // The leading slash comes off too, so `input` echoes what the reader typed
  // after /introspect/ and only differs from `link` when something was
  // genuinely normalized away (a scheme, a query, a www.).
  const rest = pathname
    .replace(/\.json$/, "")
    .replace(PREFIX, "")
    .replace(/^\/+/, "");
  return introspect(safeDecode(rest));
}

export const introspectionStatus = (result: Introspection): number =>
  result.kind === "unknown" ? 404 : 200;

/** Every entry mentioned anywhere in a result, deduped, first-mention order. */
function referencedEntries(result: Introspection): Entry[] {
  const facts: (EntryFacts | undefined)[] = [];
  if (result.kind === "address") {
    facts.push(result.hit.entry, result.hit.match.becameEntry);
    for (const other of result.otherHits)
      facts.push(other.entry, other.match.becameEntry);
  } else if (result.kind === "host") {
    for (const hit of result.addresses)
      facts.push(hit.entry, hit.match.becameEntry);
  } else if (result.kind === "redirect") {
    facts.push(
      result.targetHit?.entry,
      result.targetHit?.match.becameEntry,
      result.alsoIndexed?.entry,
      result.alsoIndexed?.match.becameEntry,
    );
  }

  const seen = new Set<string>();
  const list: Entry[] = [];
  for (const fact of facts) {
    if (!fact) continue;
    for (const entry of [fact.entry, fact.successor?.entry])
      if (entry && !seen.has(entry.id)) {
        seen.add(entry.id);
        list.push(entry);
      }
  }
  return list;
}

/**
 * Purpose-built rather than buildEnvelope(): that one describes a *view* — a set
 * of entries selected by a query, keyed by a path in indexViewPaths() — while
 * this describes a *relationship* (this address, in this bucket, of this entry).
 * `entries` stays populated anyway, for the same reason resolveCurated keeps it:
 * a consumer that only knows how to read `entries` still gets the rows, joinable
 * on `id` with the /index/*.json envelopes.
 */
export function introspectionEnvelope(result: Introspection) {
  return {
    schema: "https://aka.dog/schemas/entry.json",
    version: 1,
    link: result.link,
    input: result.input,
    generated: new Date().toISOString(),
    result,
    entries: referencedEntries(result),
  };
}
